### ISSUE TITLE
Add CDP detection support to Eth port

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/BakeBit#1]
Add CDP detection in addition to LLDP on eth0 and display on FPMS.

Jiri is looking in to this.

**Comment by jiribrejcha** [comment]
Added and submitted for testing

**Comment by jiribrejcha** [comment]
I added this feature.

**You can test it before it gets released:**

1. Backup your SD card or use a new one
2. Burn standard v1.8.4 Beta 2 image to your SD card https://github.com/WLAN-Pi/wlanpi/releases
3. cd ~/NanoHatOLED/
4. mv BakeBit BakeBit.orig
5. git clone -b master https://github.com/jiribrejcha/BakeBit.git
6. sudo reboot

**Comment by wifinigel** [comment]
Feature added by @jiribrejcha
