### ISSUE TITLE
Menu > Network > Interfaces cuts off the last digit of eth0 and wlan0 IP address

### ISSUE THREAD

**Issue by jiribrejcha** [WLAN-Pi/BakeBit#27]
**How to repro**
- Assign an IP address like 192.168.100.123 to the eth0 or wlan0 interface
- Go to Menu > Network > Interfaces
- "eth0: 192.168.100.12" will be displayed without the trailing "3"

**Suggested fix**
- Replace "eth0" with "et0"
- Replace "wlan0" with "wl0"

**Comment by wifinigel** [comment]
Fixed in the new fpms repo, Interfaces are now e0, w0, u0, or zt.
